# Please run command `pre-commit install` to install pre-commit hook
repos:
  - repo: local
    hooks:
      - id: python-fmt
        name: Python Format
        entry: make fmt-check
        language: system
        exclude: '^docs/|^tests/'
        types: [ python ]
        stages: [ commit ]
        pass_filenames: false
        args: [ ]
      - id: python-test
        name: Python Unit Test
        entry: make test
        language: system
        exclude: '^docs/|^tests/'
        types: [ python ]
        stages: [ commit ]
        pass_filenames: false
        args: [ ]
      - id: python-lint-mypy
        name: Python Lint mypy
        entry: make mypy
        language: system
        exclude: '^docs/|^tests/'
        types: [ python ]
        stages: [ commit ]
        pass_filenames: false
        args: [ ]

